# -*- coding: utf-8 -*-
"""newpanaromacore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSMSdLjJQUo7KRDPsmJIUmOUpVIk3sEP

# **OpenPanoramaMaker**

---
"""

!pip install opencv-python

!gdown --folder "https://drive.google.com/drive/folders/17kwlKrxVQ6PGsqnZ4G5hPuZ51vir5PXg?usp=sharing"

!pip install gdown

import os

folder_path = "/content/Panaromaimages"
print("Files in folder:", os.listdir(folder_path))

import cv2
image_paths = [os.path.join(folder_path, f) for f in sorted(os.listdir(folder_path)) if f.lower().endswith((".jpg", ".png", ".jpeg"))]

import cv2
import os

print(f"Number of image paths provided: {len(image_paths)}")


loaded_images = []
failed_to_load_count = 0
for i, path in enumerate(image_paths):
    img = cv2.imread(path)
    if img is None:
        failed_to_load_count += 1
        print(f"Warning: Failed to load image at path: {path}")
    else:

        target_width = 800
        height, width = img.shape[:2]
        if width > target_width:
            aspect_ratio = target_width / width
            new_height = int(height * aspect_ratio)
            img = cv2.resize(img, (target_width, new_height), interpolation=cv2.INTER_AREA)
        loaded_images.append(img)

if failed_to_load_count > 0:
    print(f"Total {failed_to_load_count} images failed to load out of {len(image_paths)}.")


images = loaded_images

if not images:
    raise ValueError("No valid images were loaded. Stitching cannot proceed.")
else:
    print(f"Successfully loaded {len(images)} images for stitching.")
    print(f"Example image size after resizing: {images[0].shape if images else 'N/A'}")

stitcher = cv2.Stitcher_create()

status, pano = stitcher.stitch(images)
if status != cv2.Stitcher_OK and status != 0:
    raise RuntimeError(f"Stitching failed with status {status}")

import matplotlib.pyplot as plt

if status == cv2.Stitcher_OK:

    plt.figure(figsize=(20,10))
    plt.imshow(cv2.cvtColor(pano, cv2.COLOR_BGR2RGB))
    plt.title("Stitched Panorama (if successful)")
    plt.axis('off')
    plt.show()
else:
    print(f"Stitching failed with status {status}. Cannot display panorama.")


print("Displaying individual resized images:")
plt.figure(figsize=(20, 15))
for i, img in enumerate(images):
    plt.subplot(4, 5, i + 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(f"Image {i+1}")
    plt.axis('off')
plt.tight_layout()
plt.show()